### ISSUE TITLE
[Feature] Run actions in CI context

### ISSUE THREAD

**Issue by goldi42** [captainhookphp/captainhook#111]
I configure my pre-commit hooks to run only against staged files.
I would run the same set of actions against all my repository files on my CI server to check the code quality.
If I call `bin/captainhook hook:pre-commit` inside my CI container, I get an error that the hook execution failed.
If I configure the action to run against all files, it work inside the CI container, but it take much time to check all files wile I am commiting files on big projects.

**Comment by sebastianfeldmann** [comment]
Hi,

I would advise to not call `captainhook` as a CI command.
Hooks often receive arguments from git that are not present if you call the hook manually.
I would think that this is not the problem here but never the less.

If you do something with staged files only in your hook and you run the same hook in CI maybe there are no staged files and that leads to an error.

If you for example check for style violations you should call the `phpcs` binary directly in your CI and not take a detour and call it via the Cap'n

This way you can execute different commands in CI and locally.
