### ISSUE TITLE
[Feature] Allow env placeholders in captainhook.(config.)json

### ISSUE THREAD

**Issue by Schrank** [captainhookphp/captainhook#127]
What do you think about allowing the definition of placeholders and then use them in the actions like {{$php-path}}? We use that in deployer and it is really nice to change run paths depending on env

**Comment by sebastianfeldmann** [comment]
I like the idea!

Since `php-path` is a config setting there should be a way to use config-settings as placeholders from the get go.
Something like...

```
    {
        "action": "{$CONFIG|php-path} ./tools/phpunit"
    }
```

But allowing users to define their own placeholders sounds useful as well.
Something like:

```
{
    "config": {
        "placeholder": {
             "phpForPHPUnit": "/some/crazy/path/to/php7.3"
        }
    }
    ...
        {
            "action": "{$PLACEHOLDER| phpForPHPUnit} ./tools/phpunit"
        }
    ...
```

We have to make sure that the user is able to overwrite placeholders locally using a `captainhook.config.json`.
Maybe we would have to improve the merge strategy there.

What do you think?

**Comment by Schrank** [comment]
I don't see a reason to differ between config and placeholders, I think it offers possibilities if one can overwrite each other - but the order must be well defined.

And I would like to copy the syntax from deployer (which looks like twig) `{{release_path}}`

Beside these thoughts, I love it!

**Comment by sebastianfeldmann** [comment]
CaptainHook already supports placeholders like `{$STAGED_FILES|of-type:php|separated-by: }` so I would stay alined with that syntax.

I don't like the idea of placeholders overwriting config values and vice versa. If you want to overwrite config settings you should use a `captainhook.config.json` otherwise this could lead to strange behavior.

**Comment by Schrank** [comment]
Makes sense - both :D

I'm happy to try to implement it, although my 🔋  is empty and I'm easy to frustrate currently :D So if you are not like "I'll do it this week and I'm super happy about it to spend my time with it" Happy to give it a try

**Comment by sebastianfeldmann** [comment]
I can start working on the config setting stuff right away. And as soon as this is finished continue with the custom placeholder stuff :)

**Comment by sebastianfeldmann** [comment]
CaptainHook 5.6.0 supports the new `CONFIG` placeholder.

    {$CONFIG|value-of:php-path}

The `CONFIG` placeholder allows access to
- git-directory
- php-path
- bootstrap

**Comment by sebastianfeldmann** [comment]
With version 5.8.0 the new `ENV` placeholder got released.

   {$ENV|value-of:MY_ENV_VAR|default:my-default-value}

The `default` part is optional.
