### ISSUE TITLE
Make written hook files relocatable

### ISSUE THREAD

**Issue by glensc** [captainhookphp/captainhook#164]
I don't like absolute path being hardcoded to hook files.

It should be possible to detect GIT_DIR (git already exports it afaik) or resolve from basename of "$0".

```
➜ pwd
/Users/glen/scm/eventum/eventum

➜ head .git/hooks/post-commit
#!/bin/sh

# installed by CaptainHook 5.10.6

INTERACTIVE="--no-interaction"

/Users/glen/Library/Caches/glen/composer/eventum/eventum/vendor/captainhook/captainhook/bin/captainhook $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:post-commit "$@" <&0
```

**Comment by sebastianfeldmann** [comment]
I like the idea :)
Any suggestions?

**Comment by glensc** [comment]
I wrote two suggestions in issue body...

**Comment by sebastianfeldmann** [comment]
This is is `post-commit` file

```
#!/bin/sh

# installed by CaptainHook 5.10.6

INTERACTIVE="--no-interaction"

bin/captainhook $INTERACTIVE --configuration=captainhook.json --bootstrap=vendor/autoload.php hook:post-commit "$@" <&0
```

You should have some special case were the Cap'n switches to an absolute path.
I have to check when this is happening.

**Comment by sebastianfeldmann** [comment]
So if your `captainhook` executable isn't located within your repositories root folder the Cap'n will use the absolute path to the executable. Not sure how to change that.

**Comment by sebastianfeldmann** [comment]
Ok I get that you can find the path to the repository root, but that's not the problem. As you said, I have access to that path at runtime anyway. The issue is that it doesn't help finding the `captainhook` executable.

If you put your `captainhook` executable outside your repository the only option is to use an absolute path. 
This is the most sustainable, because if you move your repository the absolute path to the executable should still work.
It only breaks if you move the the executable. Not ideal but again, if you have any suggestions how to solve this...

**Comment by glensc** [comment]
>  The issue is that it doesn't help finding the captainhook executable.

how come? it's $project_root/vendor/bin if installed in project deps and in $PATH otherwise.

**Comment by sebastianfeldmann** [comment]
But it doesn't have to be :)

I can place my `captainhook` executable wherever I want, in my $PATH or not. Inside or outside the repository.
And then it is not that simple to find it during execution.

**Comment by glensc** [comment]
why would you want to do that? or even specifically, why support that?

**Comment by sebastianfeldmann** [comment]
The question should be "why not support it" :)

**Comment by glensc** [comment]
> The question should be "why not support it" :)

Overengineering: Making code more complex for very low use cases does not weigh up efforts put to implement and support that.

Personally, I don't like the hardcoding because it prevents me from moving things around. Also your current way of hardcoding path breaks if my repo is in path with spaces. And no, I can not change OneDrive sync folder not to contain spaces in it.

This all could be made dynamic:
- use ../../../vendor/bin for local installs
- use PATH for global installs

And don't forget to quote shell arguments!

**Comment by glensc** [comment]
no, the binary is locatable in $project_dir/vendor/bin, just my vendor is symlink

**Comment by sebastianfeldmann** [comment]
Would a `--force-exec-path=...` option help you

Then you could install the Cap'n like this.

    vendor/bin/captainhook install --force-exec-path=vendor/bin/captainhook

**Comment by glensc** [comment]
I would say do the fallback only if `$project_dir/vendor/bin` doesn't exist. should not treat scenario differently where vendor is symlink elsewhere. the paths resolve the same way, just via symlink.

**Comment by glensc** [comment]
pardon, i wanted to write portable version. but already forgot. that is:

- `export PATH="$(git rev-parse --show-toplevel)/vendor/bin:$PATH"`
or
- `export PATH="$PATH:$(git rev-parse --show-toplevel)/vendor/bin"`

**Comment by sebastianfeldmann** [comment]
Messing with the users environment is not an option.
This would lead to unpredictable behavior if you use the Cap'n in multiple projects in different versions...

Providing the option would people like you enable to handle their edge cases.
And everybody else can just live their lives.

I'm happy to add a command option, but doing some error prone magic to replace something that currently works is not a good idea.

**Comment by glensc** [comment]
> Messing with the users environment is not an option.

I was speaking of writing that as pre-amble in hook script... it affects that single git repo only.

**Comment by sebastianfeldmann** [comment]
The part `/vendor/bin`  can not be hardcoded because of different project structures, we would have to detect the right path to the vendor directory at install time.
This whole change would only be necessary if you have a symlinked vendor directory and should only be used if that is the case.

Once again, Composer ist not the only way to install the Cap'n and even for those that use Composer not all have a `$PROJECT_ROOT/vendor` directory.


What would we have to do?

- Recognize that CaptainHook is installed via Composer
- Detect that the captainhook executable is symlinked and therefore has a different absolute path.
- Find the correct path to the symlinked vendor directory (not sure if doable without parsing `composer.json`).
- Check if the vendor directory exists.
- Write the different hook file using your export idea.

As I said you are welcome to open a pull request to provide the logic to do that.
I will most likely not invest any time in writing something like that.

I still believe that an option is the much better solution.
Much simpler.
No Magic.
Explicit.
User controlled.

**Comment by glensc** [comment]
In my case, captainhook binary is not symlinked, whole vendor directory is symlinked and all paths are still accessible the way if vendor dir is not symlink. i.e ./vendor/bin/foo still works the same way if executed from project root and to my knowledge git setups cwd or GIT_DIR the way that project_dir is correctly resolvable (via pwd, or $(dirname $(dirname $0)), or git rev-parse --show-toplevel)

I believe the option for path makes things complicated, now user has to think "do I need to use that option" as currently you just copy paste from readme.

that being said, I don't understand your negative attitude against composer paths, even given all your examples in readme assume composer paths (vendor/bin). adding vendor/bin to PATH does not break anything if the directory does not exist.

thank you for your patience, I will not be submitting any changes.

**Comment by sebastianfeldmann** [comment]
I have no positive or negative attitude agains composer paths.
I'm just pointing out that it is not that trivial to solve the issue the way you proposed to fix it.
PHP somehow receives the real path to the `captainhook` executable even if it is symlinked.
Basically that is the reason for your issue. If `CaptainHook` would use the symlinked path you would see a relative path within your hook files just like everybody else. But because `CaptainHook` is working with the real path of your `captainhook` executable (`/Users/glen/Library/Caches/glen/composer/eventum/eventum/vendor/captainhook/captainhook/bin/captainhook`) the Cap'n decides to use the absolute path as a fallback.

The only way to handle this the way you proposed is to detect at runtime that there is a symlinked path that can be used to create a relative path. I'm not sure this is doable with reasonable effort.

**Comment by sebastianfeldmann** [comment]
As I said :)
I don't want to go down that road.
And the `composer.json` isn't of any help if you do not run Composer from your repo root (which is not unusual).
Then for Composer everything looks normal but the Cap'n has to adjust to the different repo structure.

```
repo-root
  app
    src
    vendor
    composer.json
  docs
  README.md
```
