### ISSUE TITLE
¿How could i add modified files during pre-commit to the commit?

### ISSUE THREAD

**Issue by psociety** [captainhookphp/captainhook#165]
Thank you creating captain hook!!
It's the first hook manager that thinks of docker envs!

I'm running the following pre-commit config:
```json
"pre-commit": {
        "enabled": true,
        "actions": [
            {
                "action": "\\CaptainHook\\App\\Hook\\PHP\\Action\\Linting",
                "options": [],
                "conditions": []
            },
            {
                "action": "vendor/bin/psalm",
                "options": [],
                "conditions": []
            },
            {
                "action": "vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php {$STAGED_FILES|of-type:php}",
                "options": [],
                "conditions": [
                    {
                        "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
                        "args": [
                            "php"
                        ]
                    }
                ]
            }
        ]
    },
```

And i've got a minor use:
Whenever a file is being modified by php-cs-fixer, it's changes are not included in the commit. So i usually have to do 2 commits, one that contains the real changes and a second one that contains style fixes.

How could i automatically add those modified files to the commit itself?

**Comment by sebastianfeldmann** [comment]
⚠️ READ TO THE END ⚠️

You could add an action similar to this one (don't copy paste until you understand the risks).

```
            {
                "action": "git add *.php"
            },

```

or  just append it to the `cs-fixer` action.

```
            {
                "action": "vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php {$STAGED_FILES|of-type:php} && git add *.php",
                "options": [],
                "conditions": [
                    {
                        "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
                        "args": [
                            "php"
                        ]
                    }
                ]
            }
```
⚠️⚠️⚠️
But this is risky, since you have no way of knowing if `cs-fixer` changed those files or someone else did and just doesn't want to commit them yet. So you are living with the risk of committing changes you don't want to commit yet.
⚠️⚠️⚠️

The only way to do this safely is to compare the modified but not staged files BEFORE `cs-fixer` to the modified but not staged files AFTER the `cs-fixer` exection and try to figure out which ones to add to the index and which not.

If `cs-fixer`could return a list of modified files you could feed that output to the `git add` command and since you are only fixing `staged-files` you would be pretty save. But I'm not sure if `cs-fixer` can be utilized to return such a list and how to pass it the git add command. I would have to investigate that first.

The easies way that comes to mind is writing a custom PHP `Action` that runs `php-cs-fixer` parses the output and adds the changed files to the index again. But maybe there is another simple solution that can be done with some smart shell command combinations.

**Comment by sebastianfeldmann** [comment]
I completely forgot, there is in fact another way.

You can use the `PreserveWorkingTree` plugin.
What that does is, before every commit it will remove all unstated changes.
That means every unstaged change that occurs during hook execution was done by your hooks and you are "safe" to add all existing changes to the index.
After the processing of all your hooks the plugin will restore all your unstaged changes from before.

You can read about plugins in general [here](https://captainhookphp.github.io/captainhook/extend.html#plugins).

To set up the plugin just add this to your configuration
```
{
  "config": {
    "plugins": [
      {
        "plugin": "\\CaptainHook\\App\\Plugin\\Hook\\PreserveWorkingTree"
      }
    ]
  }
  ...
```

But be aware that this adds a bit of overhead to every commit because the plugin creates a git patch, cleans the working directory and then reapplies the patch to restore the changes.

**Comment by psociety** [comment]
@sebastianfeldmann following you instructions, i ended up doing:
` && git add {$STAGED_FILES|of-type:php}`

:p

**Comment by sebastianfeldmann** [comment]
That should be safe as well ;)
