### ISSUE TITLE
How to uninstall composer-plugin?

### ISSUE THREAD

**Issue by hmingv** [captainhookphp/captainhook#179]
I can't seem to find a way to uninstall in the documentation.

**Comment by hmingv** [comment]
https://captainhookphp.github.io/captainhook/composer.html

I learned to install, but don't know how to uninstall it when I don't need it.

**Comment by sebastianfeldmann** [comment]
If you want to uninstall it just remove the package from your composer configuration.
The only thing you have to do manually is to remove the hook scripts. I can't really do that for you because I don't know if you are maybe using a different tool and then I would destroy your setup.

So you have to delete `.git/hooks/ALL_HOOKS_YOU_DONT_NEED` manually.

If you haven't done anything else with git hooks remove every file in `.git/hooks` that does not end with `.sample` those are there by default. But you could delete them as well without causing any problems.

**Comment by hmingv** [comment]
Good idea, thanks for your reply.

**Comment by hmingv** [comment]
Good idea, thanks for your reply.
