### ISSUE TITLE
Linting fails when it shouldn't?

### ISSUE THREAD

**Issue by aruku** [captainhookphp/captainhook#240]
I get the following error when committing:
```bash
pre-commit:
 - \CaptainHook\App\Hook\PHP\Action\Linting                          : failed
captainhook failed executing all actions, took: 0.34s
\CaptainHook\App\Hook\PHP\Action\Linting
✘ app/src/Controller/Client/Plant/FaultsController.php
✘ app/src/Controller/Client/Plant/MapController.php
✘ app/src/Controller/Client/Plant/ReportController.php
✘ app/src/Utils/Dates.php
Linting failed: PHP syntax errors in 4 files
```

But when I run the linter manually, there is nothing:
```bash
I have no name!@aacf39c68c63:/workspace$ php -l src/Controller/Client/Plant/FaultsController.php 
No syntax errors detected in src/Controller/Client/Plant/FaultsController.php
I have no name!@aacf39c68c63:/workspace$ php -l src/Controller/Client/Plant/MapController.php    
No syntax errors detected in src/Controller/Client/Plant/MapController.php
I have no name!@aacf39c68c63:/workspace$ php -l src/Controller/Client/Plant/ReportController.php 
No syntax errors detected in src/Controller/Client/Plant/ReportController.php
I have no name!@aacf39c68c63:/workspace$ php -l src/Utils/Dates.php                              
No syntax errors detected in src/Utils/Dates.php
```

I don't see options for the linting action. How can I go about debugging this?

**Comment by aruku** [comment]
I think the problem may be in the path that is being passed to the action, because using replace in a CLI action that was failing too solved it.
Is extending the built-in action the only way to alter this path?

**Comment by sebastianfeldmann** [comment]
You can add this to your config section

```
{
    "config": {
        "verbosity": "debug"
    },
    ...
}
```

Then you should get some more information about what is going on.
The path is always relative from the git root since this it what git returns when I ask it for the changed files.

The pass not being correct is most of the time caused by some docker directory mapping. You can fix the mapping by changing the directory in your container. You can use `WORKDIR "/XYZ"` in your Docker file to fix it.

There is currently no other way then extending, but you are more then welcome to add a `path-prefix` option to the `LintingAction` and open a pull request ;)

**Comment by aruku** [comment]
Yes, it was problem with the way the directories are mounted in the container: project/app -> /workspace, project/.git -> /workspace/.git.
I ended up using a silly symlink because I don't have the time to modify all the built-in and CLI actions I'm using.
