### ISSUE TITLE
captainhook/captainhook-phar failing, prefer captainhook/captainhook in README

### ISSUE THREAD

**Issue by noteven** [captainhookphp/captainhook#245]
Hello, was having an issue today where attempting to use `captainhook/captainhook-phar` was causing a `fopen(): SSL: Handshake timed out` error after the `Downloading artifact from https://github.com/captainhookphp/captainhook/releases/download/5.22.2/captainhook.phar` portion of `composer install`, switching the dependency to `captainhook/captainhook` (and updating the `captainhook.json` to correct classpaths and reinstalling hooks) corrected this behaviour. I am not precisely sure why this occured, but it might be preferable to recommend using `captainhook/captainhook` over `captainhook/captainhook-phar` in the `README.md`?

It should be noted that visiting `https://github.com/captainhookphp/captainhook/releases/download/5.22.2/captainhook.phar` from the browser worked fine, but for some reason Composer would just timeout. I had tried deleting the `vendor` directory, running `composer clear-cache` and then running `composer install` a couple times to no avail. Even removing and readding the `captainhook/captainhook-phar` dependency did not resolve it.

**Comment by sebastianfeldmann** [comment]
What operating system are you using (php version, composer version)?
It seems that your terminal has some SSL issues.

**Comment by noteven** [comment]
Hello! I am running the commands from inside an Alpine docker container. Thing is it always worked fine, simply stopped working today - might even work again now but as switching to `captainhook/captainhook` resolved it I'll just stick to using that over `captainhook/captainhook-phar`.

**Comment by sebastianfeldmann** [comment]
Strange I just ran the install locally MacOS php 8.3 and in multiple Docker containers (Alpine 8.0 - 8.3) and it worked fine 🤔

Not sure what the issue could be.
I personally prefer the `phar` version because it does not interfere with any other dependencies. The Cap'n depends on some Symfony components and if used as a standard Composer library can trigger dependency updates that your project otherwise would not have triggered. And this could potentially lead to problems.
Unlikely but still I prefer the phar version just to be safe.
Feature wise both work the same so you can use what ever you like best.
