### ISSUE TITLE
Is it possible to disable captainhook inside docker?

### ISSUE THREAD

**Issue by alfredbez** [CaptainHookPhp/captainhook#74]
Hi there, thanks for the awesome package!

We use this in our project and we have one problem, maybe you can help us to configure it correctly.

Our repository contains a `docker-compose.yml` with some Docker images as well as the project's source code.

The structure looks like this:
```
tree -d -L 2 .
.
├── ci
├── deploy
│   └── ansible
├── docker
│   ├── apache
│   ├── db
│   └── php
├── source
│   ├── config
│   ├── src
│   ├── var
│   ├── tests
│   └── vendor
└── scripts
```

The `.git` folder is at the very top level, next to `ci`, `deploy`, etc. Our vendor folder is in `source/vendor`. We mounted the `source` folder to our PHP Docker Container to `/var/www/source/`.

The hooks on our host-machine are working as expected, but since they are not mounted on our docker-machine, we see some error message like this:
```
CaptainHook Composer Plugin
  Using CaptainHook config: captainhook.json
                                              
  [RuntimeException]                          
  Invalid git repository: /var/www/source
```

Questions:

1. Do you think mounting the `.git` directory to the PHP container is a good idea? Or do you have a better suggestion?
2. I've already configured the `git-directory`, but I can't see, where this setting is stored. I would expect it in `captainhook.json`.
3. Is it possible to have different `git-directory` configured for our host-machines and for the PHP Docker Container?

**Comment by sebastianfeldmann** [comment]
The problem here is that docker can't access the git directory.
If you do git commands and the Cap'n gets executed the Cap'n needs access to the git directory e.g. to access the temporary commit message file that ist located in your `.git` directory.

1. Mounting the `.git` directory  to `/var/www/.git` could be a solution but if you change the `.git` location and git cant see all the working tree anymore for example `git status` will give strange results. This **SHOULDN'T** be a problem since the Cap'n only operates on the index that is located inside the `.git` directory but this always deponds on how `Actions` are implemented. They **shouldn't** rely on the working tree to be intact but ...

2. You can either use the `--git-directory` command option or put it in the configuration file

```
{
  "config": {
    "git-directory": "../.git"
  }
}
```

3. So you have machines that are running PHP locally and ones that use docker to execute it.
Currently you cant' configure both at the same time. What you can do is configure the default scenaria and everybody using the other variant hast to install the hooks with the `--git-directory` option since it superseeds the configuration value.

**Comment by alfredbez** [comment]
Thanks for the fast feedback! Maybe we try to mount the whole project-folder to something like `/project` inside the Docker Container.

**Comment by sebastianfeldmann** [comment]
That would solve the problem. But I would not use this setting in production. In case you are running docker in production as well make sure to not put all that maybe sensitive data into your container ;)

**Comment by sebastianfeldmann** [comment]
I will close this for now, but if you have any further questions feel free to re-open this issue or open a new one.
