### ISSUE TITLE
Post commit hooks

### ISSUE THREAD

**Issue by houssemz** [CaptainHookPhp/captainhook#75]
I'am tried to use the post-commit hook but I can't unfortunately. This may be a new feature ?

**Comment by sebastianfeldmann** [comment]
Can you post your `captainhook.json`?

It should contain something like this.
```
    "post-commit": {
        "enabled": true,
        "actions": [
            {"action": "my-command"}
        ]
    },
```

**Comment by houssemz** [comment]
I am using `"captainhook/captainhook": "^1.2"` for many PHP version constraint and this is my `captainhook.json` :

```json
{
    "commit-msg": {
        "enabled": false,
        "actions": [
        ]
    },
    "pre-commit": {
        "enabled": false,
        "actions": [
        ]
    },
    "pre-push": {
        "enabled": false,
        "actions": [
        ]
    }
}
```

**Comment by sebastianfeldmann** [comment]
Version 1.X that is something.
I'm not sure but I think `post-commit`, `post-merge` and `post-checkout` got introduced in version 3.

Sadly it is not possible for me to back port new features to old versions.
Since version 4 I'm heavily making use of PHP7+ features.

I'm sure I don't have to remind you that it seems that you are working on an unsupported PHP version. Everything below 7.0 has reached its end of life as you can see [here](https://www.php.net/supported-versions.php). And even 7.0 and 7.1 recently passed their end of life date.

I can only encourage you to upgrade your software to a supported PHP version.

I try to support all supported PHP versions with all of my libraries, but supporting older versions is sadly not possible for me :(

**Comment by sebastianfeldmann** [comment]
A solution for you could be using the latest `CaptainHook` PHAR release and execute it inside a docker container.

I know it sounds a bit much, but this way you can decouple your tooling PHP versions from your application PHP version.

Sorry I can't be of any more help.

**Comment by houssemz** [comment]
I am aware that unfortunately my company PHP version is very outdated ... I will show to my manager this decision .. 
Thank you so much, especially for being so rapidly in response.
Houssem.
