### ISSUE TITLE
Space in captainhook.json path leading to not found in 5.1.2

### ISSUE THREAD

**Issue by iquito** [CaptainHookPhp/captainhook#79]
Just tried it with 5.1.2, the same issue as described in https://github.com/CaptainHookPhp/captainhook/issues/78 still exists.

**Comment by sebastianfeldmann** [comment]
Jikes...

I escaped the arguments, bt did not think about the path to the binary 🙈
In plugin version 5.1.3 now the arguments for configuration and repo are escaped and the binary  path is also escaped.

Since `Composer` still executes the old plugin even if it is updated. you have to run composer update 2 times to actually see it work :/

Hope now it works

**Comment by iquito** [comment]
Yep it works now, thanks! No worries, I could have always spammed more issues until it works ;-)

**Comment by sebastianfeldmann** [comment]
Thanks for the feedback 👍
