### ISSUE TITLE
FileChanged BC break 4.X => 5.X

### ISSUE THREAD

**Issue by boesing** [CaptainHookPhp/captainhook#82]
Hey there,

as there was no migration path available for 4.X to 5.X, I recently realized that the `FileChanged` hook introduces a `Constrained` interface which massively slows down our workflow.

In 4.X, the `FileChanged` got executed as expected for *any* hook, in 5.X its only executed for `post-merge` and `post-checkout`.

As the `FileChanged` is not "applicable" for all those other hooks, *any* hook is executed even if no file changed.

What is the reason behind that decision?

**Comment by sebastianfeldmann** [comment]
You are right, now `FileChanged` is only executed on `post-merge` and `post-checkout`.
This is because `FileChanged` does not work for any other hook.

The way `FileChanged\All` and `FileChanged\Any` are implemented make them only applicable for `post-merge` and  `post-checkout` hooks.

Both of them are using `git diff` to detect the changed files. And only `post-checkout` and `post-merge` provide the required `ID`s to get a valid response.

It was "working" with other hooks before but not working at all, the conditions where always false.

**Comment by boesing** [comment]
So there is no diff in a `pre-commit` hook? 
Thats interesting. 


Any suggestion how to receive the diff in a pre-commit hook of those files which are contained within the commit?

Would also know if there is a way to get all changed files in a pre-push hook. Having a diff between `HEAD` and repository version would be great.

**Comment by sebastianfeldmann** [comment]
It is possible but the implementation must be different.
You have to check the `index` to get the file "that will change" in the upcoming commit.
This is done manually in some Hooks like the `listing` hook.
Currently there is no `Condition` implementation because I haven't figured out a nice way of naming an implementing it without breaking the current `FileChanged` implementations :/

**Comment by boesing** [comment]
I'll give it a try and if I found a way, I'll contribute back. Thanks so far.

**Comment by sebastianfeldmann** [comment]
There is a condition specific for `pre-commit` named `FilesStaged\OfType` it works similar as `FilesChanged\Any`. The condition works in a `pre-commit` hook and will only execute the hook if a file of a given file suffix is staged for commit. I'll add `Any` and `All` there today.

**Comment by sebastianfeldmann** [comment]
I just released version 5.2.0 with the new Staged `All` and `Any` conditions that you can use in `pre-commit` hooks.
